<a href="https://colab.research.google.com/github/Yaghs/datasci_1_loading/blob/main/HHA_507_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**This code cell is importing pandas as pd, and json**

without these you cannot call the pandas library and its respective functions to read the files

without importing json library, you cannot read JSON either.

In [1]:
import pandas as pd

**THE CELL BELOW IS ASSIGINING THE CSV FILES FROM THEIR RELATIVE PATHS TO THE FOLLOWING VARIABLES csv_data1, csv_data2, csv_data3**

In [2]:
csv_data1 = '/content/Data/Inpatient_Rehabilitation_Facility-General_Information_Jun2026_b.csv'
csv_data2 = '/content/Data/Inpatient_Rehabilitation_Facility-National_Data_Jun2026_b.csv'
csv_data3 = '/content/Data/Inpatient_Rehabilitation_Facility-Provider_Data_Jun2026_b.csv'

**THE CELL BELOW IS ASSIGNING THE XLSX FILES TO FROM THEIR RELATIVE PATHS TO THE FOLLOWING VARIABLES: xlsx_data1, xlsx_data2, xlsx_data3**

In [3]:
xlsx_data1 = '/content/Data/emergency-department-volume-and-capacity-2021-2023.xlsx'
xlsx_data2 = '/content/Data/hci_unemployment_290_ca_re_co_cd_pl_ct-5-22-14-ada.xlsx'
xlsx_data3 = '/content/Data/supplier-diversity-in-california-hospital-procurements-2021-2023-dashboard-data.xlsx'

**THE CELL BELOW IS ASSIGNING THE JSON FILES FROM THEIR RELATIVE PATHS TO THE FOLLOWING VARIABLES: json_data1, json_data2, json_data3**

In [4]:
json_data1 = '/content/Data/MTA-headcount-2024.json'
json_data2 = '/content/Data/MTA-subway-delays-2020.json'
json_data3 = '/content/Data/retail-food-stores.json'

**csv_data1 represents the following:**

General information about about Inpatient rehab facilities, data extracted on june 2026.

**Columns**




**1.   CMS Certification Number (CCN)**

      *  contains a list of unique six digit ID codes assigned by the centers of medicare & medicaid services (CMS). they are certified to provide medicare and medicaid services
**2.   Provider Name**

      *   lists the names of every rehab center in the dataset
**1.   Address Line 1**

       *   lists the physical location of the rehab center
**2.   Address Line 2**

       *   lists any additional addresses related to a specific rehab center (EXAMPLE: Address 1 can be 123 apple street, address 2 can be Tower III, 5th Floor)
**1.   City/Town**

       *   lists which city or town the rehab center is located
**2.   State**

       *   lists which state the rehab center is located
**1.   ZIP Code**

       *   lists the ZIP code of each rehab center
**2.   County/Parish**

       *   lists which county each rehab center is located at (EXAMPLE: NASSAU, SUFFOLK)
**1.   Telephone Number**

       *   lists the telephone number assigned to the rehab center to contact. (patients could be using it to set up appointments)
**2.   CMS Region**

       *  lists the region number assigned to every rehab facility. it serves as the local presence of the federal government, to provide regulatory oversight, enforce compliance, handle medicare/medicaid reimbursement policies and offer guidance to healthcare providers.
**2.   Ownership Type**

       *   lists wether if the rehab facility is for profit, non-profit or a government facility

**2.   Certification Date**

       *   lists when each rehab center have recieved their CMS Ceritficiation




**What does the code do?**

first, variable df1 is initialized and is assigned to the pd module using dot notation to call the read_csv function passing csv_data1 as an argument.

we need this line of code so that pandas can read our dataset which in this case is a CSV file

second, we call our assigned variable and use dot notation again to call the head function with an argument of 11

NOTE: Python uses zero indexing, meaning anything like lists/arrays start at 0.

In [5]:
df1 = pd.read_csv(csv_data1)
df1.head(11)

,CMS Certification Number (CCN),Provider Name,Address Line 1,Address Line 2,City/Town,State,ZIP Code,County/Parish,Telephone Number,CMS Region,Ownership Type,Certification Date
0,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,For profit,10/01/1983
1,013028,ENCOMPASS REHABILITATION HOSPITAL OF MONTGOMERY,4465 NARROW LANE RD,-,MONTGOMERY,AL,36116,Montgomery,(334) 284-7821,4,For profit,05/11/1987
2,013029,ENCOMPASS HEALTH REHABILITATION HOSPITAL NORTH AL,1490 HIGHWAY 72 E,-,HUNTSVILLE,AL,35811,Madison,(205) 535-2300,4,For profit,06/04/1987
3,013030,ENCOMPASS HEALTH REHABILITATION HOSPITAL OF DO...,1736 EAST MAIN STREET,-,DOTHAN,AL,36301,Houston,(334) 712-6333,4,For profit,05/12/1994
4,013031,ENCOMPASS HEALTH REHABILITATION HOSPITAL OF SH...,900 OAK MOUNTAIN COMMONS LANE,-,PELHAM,AL,35124,Shelby,(205) 216-7621,4,For profit,05/25/2018
5,013032,ENCOMPASS HEALTH REHABILITATION HOSPITAL GADSDEN,801 GOODYEAR AVE,-,GADSDEN,AL,35903,Etowah,(256) 439-5000,4,For profit,08/14/2001
6,013033,REHABILITATION HOSPITAL OF PHENIX CITY,3715 US HIGHWAY 431 NORTH,-,PHENIX CITY,AL,36867,Russell,(334) 732-2200,4,For profit,11/12/2003
7,01T011,ST. VINCENTS EAST REHABILITATION CENTER,50 MEDICAL PARK EAST DRIVE,-,BIRMINGHAM,AL,35235,Jefferson,(205) 838-3672,4,Non-profit,04/30/1998
8,01T029,EAMC- LANIER,2000 PEPPERELL PARKWAY.,-,OPELIKA,AL,36801,Lee,(502) 596-6346,4,Government,10/01/2016
9,01T033,SPAIN REHABILITATION CENTER,SRC 223E,-,BIRMINGHAM,AL,35249,Jefferson,(205) 934-4940,4,Government,10/01/1997
10,01T092,DCH REHABILITATION CENTER,"809 UNIVERSITY BLVD, EAST",-,TUSCALOOSA,AL,35401,Tuscaloosa,(205) 333-4362,4,Government,05/01/2011

**csv_data2 represents the following:**

General information about about Inpatient rehab facilities, data extracted on june 2026.

**Columns**




**1.   CMS Certification Number (CCN)**

      *  lists the CMS certification number (CCN) that is used to identify the facility listed. However, since this is the national data set, the CCN is listed as “Nation.”
**2.   Measure Code**

      *   The measure code consists of the CMS ID (prefix) and the variable name (suffix) for the corresponding measure score. Example = I_022_01_NATL_OBS_RATE. We need this to ensure absolute uniqueness, calrity and system inteoperability across healthcare data reporting

**1.   Score**

       *   lists the measure score for the corresponding measure code
**2.   Footnote**

       *   lists a specific numeric code that explains why a facility performance score, quality measure or patient count is missing or suppressed (in this dataset, non exist)
**1.   Start Date**

       *   lists the start date of the reporting period for the corresponding measure code and score
**2.   End Date**

       *   lists the end date of the reporting period for the corresponding measure code and score
**1.   Measure Date Range**

       *   lists the start date through the end date of the reporting period(s) for the corresponding measure code and score. Only reporting periods that are "split" are populated and represented using a semicolon betweenthe split periods (for example: 01/01/2026-9/19/2026;)



**What does the code do?**

first, variable df2 is initialized and is assigned to the pd module using dot notation to call the read_csv function passing csv_data2 as an argument.

we need this line of code so that pandas can read our dataset which in this case is a CSV file

second, we call our assigned variable and use dot notation again to call the head function with an argument of 11

NOTE: Python uses zero indexing, meaning anything like lists/arrays start at 0.

In [6]:
df2 = pd.read_csv(csv_data2)
df2.head(11)

,CMS Certification Number (CCN),Measure Code,Score,Footnote,Start Date,End Date,Measure Date Range
0,NATION,I_006_01_NATL_SIR,1.005,-,07/01/2024,06/30/2025,-
1,NATION,I_011_05_NATL_OBS_RATE,64.84,-,10/01/2024,09/30/2025,-
2,NATION,I_012_06_NATL_OBS_RATE,62.03,-,10/01/2024,09/30/2025,-
3,NATION,I_013_01_NATL_OBS_RATE,0.14,-,10/01/2024,09/30/2025,-
4,NATION,I_015_01_NATL_SIR,0.331,-,07/01/2024,06/30/2025,-
5,NATION,I_016_01_NATL_OBS_RATE,77.10,-,10/01/2024,03/31/2025,-
6,NATION,I_017_01_PPR_PD_NATL_OBS_RATE,9.21,-,10/01/2022,09/30/2024,-
7,NATION,I_017_01_PPR_PD_N_BETTER_NATL,19,-,10/01/2022,09/30/2024,-
8,NATION,I_017_01_PPR_PD_N_NO_DIFF_NATL,"1,101",-,10/01/2022,09/30/2024,-
9,NATION,I_017_01_PPR_PD_N_TOO_SMALL,19,-,10/01/2022,09/30/2024,-
10,NATION,I_017_01_PPR_PD_N_WORSE_NATL,55,-,10/01/2022,09/30/2024,-

**csv_data3 represents the following:**

General information about about Inpatient rehab facilities, data extracted on june 2026.

**Columns**




**1.   CMS Certification Number (CCN)**

      *  lists the CMS certification number (CCN) is used to identify the facility listed
**2.   Provider Name**

      *   lists the Name of the facility

**3.   Address Line 1**

       *   lists the first ine of the address of the facility
**4.   Address Line 2**

       *   lists the second line of the address of the facility
**5.   City/Town**

       *   lists the name of the city/town where the facility is located
**6.   State**

       *   lists the two character postal code where the facility is located
**7.   ZIP Code**

       *   lists the five-digit postal ZIP code where the facility is located

**8.   Telephone Number**

       *   lists the  ten-digit telephone number of the facility. The format is (xxx) yyy-zzzz.

**9.   CMS Region**

       *   lists the  CMS region where the facility is located. Below is a key to the location of the regional offices and the states covered by each CMS region:
**10.   Measure Code**

       *   lists the measure code consists of the CMS ID (prefix) and the variable name (suffix) for the corresponding measure score. Example = I_022_01_ADJ_RATE
**11.   Score**

       *   lists the measure score for the corresponding measure code
**12.   Footnote**

       *    lists a specific numeric code that explains why a facility performance score, quality measure or patient count is missing or suppressed

       in this case

       1 = The number of cases/patient stays is too small to report.
       2 = Data not available for this reporting period.
       3 = Results are based on a shorter time period than required.
       4 = Data suppressed by CMS for one or more quarters.
       5 = Data not submitted for this reporting period.
       6 = The lower limit of the confidence interval cannot be calculated if the number of observed infections equals zero.
       7 = Results cannot be calculated for this reporting period.
       8 = This inpatient rehabilitation facility isn't required to submit quality data to Medicare because it’s paid under a Medicare waiver program.

**13.   Start Date**

       *   lists the start date of the reporting period for the corresponding measure code and score
**14.   End Date**

       *   lists The end date of the reporting period for the corresponding measure code and score
**15.   Measure Date Range**

       *   lists the start date through the end date of the reporting period(s) for the corresponding measure code and score. Only reporting periods that are "split" are populated and represented using a semicolon betweenthe split periods (for example: 01/01/2026-9/19/2026;)
.


**What does the code do?**

first, variable df3 is initialized and is assigned to the pd module using dot notation to call the read_csv function passing csv_data3 as an argument.

we need this line of code so that pandas can read our dataset which in this case is a CSV file

second, we call our assigned variable and use dot notation again to call the head function with an argument of 11

NOTE: Python uses zero indexing, meaning anything like lists/arrays start at 0.

In [7]:
df3 = pd.read_csv(csv_data3)
df3.head(11)

,CMS Certification Number (CCN),Provider Name,Address Line 1,Address Line 2,City/Town,State,ZIP Code,County/Parish,Telephone Number,CMS Region,Measure Code,Score,Footnote,Start Date,End Date,Measure Date Range
0,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_CI_LOWER,0.368,-,07/01/2024,06/30/2025,-
1,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_CI_UPPER,2.791,-,07/01/2024,06/30/2025,-
2,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_COMP_PERF,No Different than the National Benchmark,-,07/01/2024,06/30/2025,-
3,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_DOPC_DAYS,"3,200",-,07/01/2024,06/30/2025,-
4,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_ELIGCASES,3.457,-,07/01/2024,06/30/2025,-
5,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_NUMERATOR,4,-,07/01/2024,06/30/2025,-
6,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_006_01_SIR,1.157,-,07/01/2024,06/30/2025,-
7,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_013_01_DENOMINATOR,"1,770",-,10/01/2024,09/30/2025,-
8,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_013_01_NUMERATOR,4,-,10/01/2024,09/30/2025,-
9,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_013_01_OBS_RATE,0.23,-,10/01/2024,09/30/2025,-
10,013025,ENCOMPASS HEALTH LAKESHORE REHABILITATION HOSP...,3800 RIDGEWAY DRIVE,-,BIRMINGHAM,AL,35209,Jefferson,(205) 868-2000,4,I_011_05_DENOMINATOR,"1,557",-,10/01/2024,09/30/2025,-

**xlsx_data1 represents the following:**

Emergency Department ratio of encounters and treatment staions to represent the ED burden. Encounters are broken down by health related conditions such as COVID-19, Cancer, Sepsis, Mental Health

**Columns**

**1.   oshpd_id**

      *  lists the OSHPD ID of the facility
**2.   FacilityName2**

      *   lists the name of the faciliy

**3.   CountyName**

       *   lists the County the facility is located in
**4.   system**

       *   lists the hospital system the facility is a part of
**5.   LICENSED_BED_SIZE**

       *   lists the  category(range) of ED treatment stations
**6.   HospitalOwnership**

       *   lists the  Facility ownership category
**7.   UrbanRuralDesi**

       *   lists the area designation for the location of the facility

**8.   TEACHINGDesignation**

       *   lists the  rows that indicate if a facility is a teaching or non-teaching facility

**9.   Category**

       *   lists the  health relaion condition
**10.   Tot_ED_NmbVsts**

       *   lists the total number of ED Encounters for the facility
**11.   EDStations**

       *   lists the number of ED Treatment stations
**12.   EDDXCount**

       *    lists the number of ED visits for the specific category (health-related condition)

**13.   LATITUDE**

       *   lists the facility latitude
**14.   LONGITUDE**

       *   lists The facility longitude
**15.   PrimaryCareShortageArea**

       *   lists wether if a facility is in a Health Professional Shortage Area for Primary Care
**16.   MentalHealthShortageArea**

       *   lists wether if a facility is in a health Professional Shortage area for mental health
**17.   Visits_Per_Station**

       *   lists the number of ED visits per ED station in a facility

**18.   Year**

       *   lists the year of the data


**What does the code do?**

first, variable df4 is initialized and is assigned to the pd module using dot notation to call the read_excel function passing xlsx_data1 as an argument.

we need this line of code so that pandas can read our dataset which in this case is a XLSX file

second, we call our assigned variable and use dot notation again to call the head function with an argument of 11

NOTE: Python uses zero indexing, meaning anything like lists/arrays start at 0.

In [8]:
df4 = pd.read_excel(xlsx_data1)
df4.head(11)

,oshpd_id,FacilityName2,CountyName,system,year,LICENSED_BED_SIZE,HospitalOwnership,UrbanRuralDesi,TEACHINGDesignation,Category,Tot_ED_NmbVsts,EDStations,EDDXCount,LATITUDE,LONGITUDE,PrimaryCareShortageArea,MentalHealthShortageArea,Visits_Per_Station
0,106010735,Alameda Hospital,Alameda,Alameda Health System,2022,100-149,Government,Urban,Non-Teaching,Active COVID-19,13579,12.0,520,37.762660,-122.253991,No,No,43.333333
1,106010739,Alta Bates Summit Medical Center – Alta Bates ...,Alameda,Sutter Health,2022,300-499,Nonprofit,Urban,Non-Teaching,Active COVID-19,29760,22.0,1177,37.856450,-122.257430,No,No,53.500000
2,106010776,UC San Francisco Benioff Children's Hospital O...,Alameda,NaN,2022,150-199,Nonprofit,Urban,Teaching,Active COVID-19,35062,40.0,1822,37.837220,-122.267470,No,No,45.550000
3,106010846,Highland Hospital,Alameda,Alameda Health System,2022,200-299,Government,Urban,Non-Teaching,Active COVID-19,66095,53.0,2109,37.799250,-122.231380,No,No,39.792453
4,106010937,Alta Bates Summit Medical Center,Alameda,Sutter Health,2022,300-499,Nonprofit,Urban,Non-Teaching,Active COVID-19,29336,30.0,1325,37.821060,-122.262570,No,No,44.166667
5,106010987,Washington Hospital – Fremont,Alameda,NaN,2022,300-499,Government,Urban,Non-Teaching,Active COVID-19,43964,39.0,3013,37.558470,-121.980060,No,No,77.256410
6,106014050,Stanford Health Care Tri-Valley,Alameda,NaN,2022,150-199,Nonprofit,Urban,Non-Teaching,Active COVID-19,28620,17.0,1378,37.692060,-121.880950,No,No,81.058824
7,106014132,Kaiser Foundation Hospital – Fremont,Alameda,Kaiser Foundation Hospitals,2022,100-149,Nonprofit,Urban,Non-Teaching,Active COVID-19,38960,18.0,1487,37.550550,-121.974830,No,No,82.611111
8,106014233,Eden Medical Center,Alameda,Sutter Health,2022,100-149,Nonprofit,Urban,Non-Teaching,Active COVID-19,31062,22.0,1467,37.698377,-122.087406,No,No,66.681818
9,106014326,Kaiser Foundation Hospital – Oakland/Richmond,Alameda,Kaiser Foundation Hospitals,2022,300-499,Nonprofit,Urban,Non-Teaching,Active COVID-19,120088,80.0,4883,37.824020,-122.257910,No,No,61.037500
10,106014337,Kaiser Foundation Hospital – San Leandro,Alameda,Kaiser Foundation Hospitals,2022,200-299,Nonprofit,Urban,Non-Teaching,Active COVID-19,69343,40.0,2893,37.706110,-122.169170,No,No,72.325000

**xlsx_data2 represents the following:**

data on the percent of the population in the labor force who are unemployed for California, its regions, counties, county divisions, cities/towns and cencus tracts based on data from Local Ara Unemployment statistics (LAUS), Bureau of labor statistics (BLS), U.S. Census Bureau and American Community Survey (ACS).

**Columns**

**1.   ind_id**

      *  lists the indicator ID
**2.   ind_definition**

      *   lists the definition of indicator in plain language

**3.   reportyear**

       *   lists the Year(s) that the indicator was reported
**4.   race_eth_code**

       *   lists the numeic ode for a race/ethnicity group
**5.   race_eth_name**

       *   lists the  name of race/ethnic
**6.   geotype**

       *   lists the type of geographic unit
**7.   geotypevalue**

       *   lists the value of geographic unit

**8.   geoname**

       *   lists the name of geographic unit
**9.   county_fips**

       *   lists the FIPS code of county that geotype is in

**10.   county_name**

       *   lists the name of county that geotype is in
**11.   region_name**

       *   lists the Metropolitan planning Organization (MPO)-based region name
**12.   region_code**

       *   lists the MPO based region code
**13.   Unemployment**

       *    lists the unemployment population

**14.   Labor_force**

       *   lists the population in the labor force
**15.   Unemployment_rate**

       *   lists The value based on the formula: unemployment / Labor_force * 100
**16.   II_95ci**

       *   lists the lower limit of 95% confidence interval
**17.   ul_95ci**

       *   lists the upper limit of 95% confidence interval
**18.   se**

       *   lists the standard error of percent

**19.   rse**

       *   lists the relative standard error (using the formula: se/percent * 100) expressed as a percent
**20.   CA_decile**

       *   lists the California decile
**21.   CA_RR**

       *   lists the rate ratio to california rate
**22.   version**

       *   lists the date/timestamp of version of data


**What does the code do?**

first, variable df5 is initialized and is assigned to the pd module using dot notation to call the read_excel function passing xlsx_data2 as an argument.

we need this line of code so that pandas can read our dataset which in this case is a XLSX file

second, we call our assigned variable and use dot notation again to call the head function with an argument of 11

NOTE: Python uses zero indexing, meaning anything like lists/arrays start at 0.

In [9]:
df5 = pd.read_excel(xlsx_data2)
df5.head(11)

,ind_id,ind_definition,reportyear,race_eth_code,race_eth_name,geotype,geotypevalue,geoname,county_fips,county_name,...,Unemployment,Labor_force,Unemployment_rate,ll_95ci,ul_95ci,se,rse,place_decile,ca_rr,version
0,290,Unemployment rate,2004,9.0,Total,CA,6.0,California,NaN,NaN,...,1089657.0,17444436.0,6.2,NaN,NaN,NaN,NaN,NaN,1.0,2014-05-22 11:47:47
1,290,Unemployment rate,2005,9.0,Total,CA,6.0,California,NaN,NaN,...,952559.0,17544763.0,5.4,NaN,NaN,NaN,NaN,NaN,1.0,2014-05-22 11:47:47
2,290,Unemployment rate,2006,9.0,Total,CA,6.0,California,NaN,NaN,...,865423.0,17686689.0,4.9,NaN,NaN,NaN,NaN,NaN,1.0,2014-05-22 11:47:47
3,290,Unemployment rate,2006-2010,1.0,AIAN,CA,6.0,California,NaN,NaN,...,9673.0,70286.0,13.8,12.608511,14.991489,0.607903,4.405092,NaN,1.0,2014-05-22 11:47:47
4,290,Unemployment rate,2006-2010,3.0,AfricanAm,CA,6.0,California,NaN,NaN,...,142776.0,1012992.0,14.1,13.742553,14.457447,0.182371,1.293410,NaN,1.0,2014-05-22 11:47:47
5,290,Unemployment rate,2006-2010,2.0,Asian,CA,6.0,California,NaN,NaN,...,175048.0,2452234.0,7.1,6.980851,7.219149,0.060790,0.856201,NaN,1.0,2014-05-22 11:47:47
6,290,Unemployment rate,2006-2010,4.0,Latino,CA,6.0,California,NaN,NaN,...,666317.0,6270852.0,10.6,10.480851,10.719149,0.060790,0.573493,NaN,1.0,2014-05-22 11:47:47
7,290,Unemployment rate,2006-2010,7.0,Multiple,CA,6.0,California,NaN,NaN,...,41077.0,320235.0,12.8,12.204255,13.395745,0.303951,2.374620,NaN,1.0,2014-05-22 11:47:47
8,290,Unemployment rate,2006-2010,5.0,NHOPI,CA,6.0,California,NaN,NaN,...,7636.0,69487.0,11.0,9.927660,12.072340,0.547112,4.973750,NaN,1.0,2014-05-22 11:47:47
9,290,Unemployment rate,2006-2010,8.0,Other,CA,6.0,California,NaN,NaN,...,5343.0,54725.0,9.8,8.608511,10.991489,0.607903,6.203089,NaN,1.0,2014-05-22 11:47:47
10,290,Unemployment rate,2006-2010,9.0,Total,CA,6.0,California,NaN,NaN,...,1642405.0,18274871.0,9.0,8.880851,9.119149,0.060790,0.675447,NaN,1.0,2014-05-22 11:47:47

**xlsx_data3 represents the following:**

dataset containing hospital supplier diversity plans.

**Columns**

**1.   HCAI_ID**

      *  lists the HCAI/OSHPD Facility ID
**2.   Year**

      *   lists the reporting year

**3.   Hospital_Name**

       *   lists the hospital name
**4.   Urban_Rural_Designation**

       *   lists the designation determiend by the Medical Service Study Area Designation (MSSA)
**5.   Require_Certification**

       *   lists whether the hospital faility requires a diverse business to be certified in order to include their business as part of their supplier Diversity reporting
**6.   County**

       *   lists the county
**7.   Hospital_ownership**

       *   lists the type of control

**8.   Category**

       *   lists the indication of diverse business enterprise category  
**9.   Procurement**

       *   lists the purchase or lease of supplies, services, equipment, and capital expenditures related to buildings and fixed equipment during the previous calendar year

**10.   Procurement_Type*

       *   lists the indication of the type of procurement
**11.   Disproportionate_Share_Hospital**

       *   lists the disproporationate share hospitals serve low-income patients and recive payments from CMS to cover the costs of providing care to uninsured patients.  

**What does the code do?**

first, variable df6 is initialized and is assigned to the pd module using dot notation to call the read_excel function passing xlsx_data3 as an argument.

we need this line of code so that pandas can read our dataset which in this case is a XLSX file

second, we call our assigned variable and use dot notation again to call the head function with an argument of 11

NOTE: Python uses zero indexing, meaning anything like lists/arrays start at 0.

In [10]:
df6 = pd.read_excel(xlsx_data3)
df6.head(11)

,HCAI_ID,Year,Hospital_Name,Urban_Rural_Designation,Require_Certification,County,Hospital_Ownership,Category,Procurement,Procurement_Type,Disproportinate_Share_Hospital
0,106190034,2021,ANTELOPE VALLEY HOSPITAL,Urban,Yes,Los Angeles,District,African American,1686.0,Tier I,Yes
1,106190034,2021,ANTELOPE VALLEY HOSPITAL,Urban,Yes,Los Angeles,District,Asian Pacific American,18285.0,Tier I,Yes
2,106190034,2021,ANTELOPE VALLEY HOSPITAL,Urban,Yes,Los Angeles,District,Disabled Veteran,NaN,Tier I,Yes
3,106190034,2021,ANTELOPE VALLEY HOSPITAL,Urban,Yes,Los Angeles,District,Hispanic American,47611.0,Tier I,Yes
4,106190034,2021,ANTELOPE VALLEY HOSPITAL,Urban,Yes,Los Angeles,District,Less Duplicated Amount,41979.0,Tier I,Yes
5,106190034,2021,ANTELOPE VALLEY HOSPITAL,Urban,Yes,Los Angeles,District,LGBT,NaN,Tier I,Yes
6,106190034,2021,ANTELOPE VALLEY HOSPITAL,Urban,Yes,Los Angeles,District,Native American,0.0,Tier I,Yes
7,106190034,2021,ANTELOPE VALLEY HOSPITAL,Urban,Yes,Los Angeles,District,Unknown Minority,449121.0,Tier I,Yes
8,106190034,2021,ANTELOPE VALLEY HOSPITAL,Urban,Yes,Los Angeles,District,Women,NaN,Tier I,Yes
9,106190034,2021,ANTELOPE VALLEY HOSPITAL,Urban,Yes,Los Angeles,District,African American,NaN,Tier II,Yes
10,106190034,2021,ANTELOPE VALLEY HOSPITAL,Urban,Yes,Los Angeles,District,Asian Pacific American,NaN,Tier II,Yes

**json_data1 represents the following:**

dataset containing actual and projected monthly headcount data, obtained from the MTA's annual budgeting process for each month of a fiscal year, categorized by budget scenario, agency, function, occupational group, and segmented by non-reimbursable (NREIMB) or reimbursable (REIMB) positions.

**Columns**

**1.   :id**

      *  lists the unique name associated with the row so systems can find, update, or delete that exact record should it be required for JSON.
**2.   :version**

      *   lists how the row is tracked for changes in content ensuring the JSON code knows how to process older or newer formats safely

**3.   :created_at**

       *   lists the timestamp of when the data was first added for JSON
**4.   :updated_at**

       *   lists the timestamp of when the data was updated for JSON
**5.   fiscal_year**

       *   lists the fiscal year of the data
**6.   month**

       *   lists the month of the data, rounded up to the first day of the month. EX: 2023-01-01
**7.   scenario**

       *   lists what type of budget scenario was associated with the row for wether if the data is actuals or budgeted

**8.   financial_plan_year**

       *   lists the year the budget scenario was published. for actuals, financial plan year will always equal the fiscal year.

**9.   	expense_type**

       *   lists whether if the expense type is reimbursable or non-reimburseable

**10.  	agency**

       *   lists which agency did this come from within the MTA? EX: LIRR, NYCT
**11.   	function**

       *   lists the wether if the budget came from operations, administration, maintenance or engineering   
**11.   	occupational_group**

       *   lists wether if the occupational group is managers/supervisors, professional/Technical/Clerical or Operational Hourlies
**11.   	positions**

       *   lists the number of positions can be a decimal or a negative.  

**What does the code do?**

first, variable df7 is initialized and is assigned to the pd module using dot notation to call the read_excel function passing json_data1 as an argument.

we need this line of code so that pandas can read our dataset which in this case is a JSON file

second, we call our assigned variable and use dot notation again to call the head function with an argument of 11

NOTE: Python uses zero indexing, meaning anything like lists/arrays start at 0.
NOTE: you do not need to import JSON, just use pandas's read_json function

In [11]:
df7 = pd.read_json(json_data1)
df7.head(11)

,:id,:version,:created_at,:updated_at,fiscal_year,month,scenario,financial_plan_year,expense_type,agency,function,occupational_group,positions
0,row-d2a3_eedc_tsm6,rv-bkxv-7xuh~ca3i,2026-09-01 18:37:12.606000+00:00,2026-09-01 18:37:12.606000+00:00,2026,2026-07-01T00:00:00.000,Actual,2026,NREIMB,LIRR,Maintenance,Operational Hourlies,2738.30
1,row-6bhh.n5zt.k6je,rv-azkc-aswk.4fw2,2026-09-01 18:37:12.606000+00:00,2026-09-01 18:37:12.606000+00:00,2026,2026-07-01T00:00:00.000,Actual,2026,REIMB,MTABC,Engineering,Managers/Supervisors,11.00
2,row-zxfp-duyv.t6dx,rv-5tim.njhx~iueh,2026-09-01 18:37:12.606000+00:00,2026-09-01 18:37:12.606000+00:00,2026,2026-07-01T00:00:00.000,Actual,2026,REIMB,MNR,Public Safety,Managers/Supervisors,0.00
3,row-7zac~326i~ddvt,rv-tn97-gg6k~dghg,2026-09-01 18:37:12.606000+00:00,2026-09-01 18:37:12.606000+00:00,2026,2026-07-01T00:00:00.000,Actual,2026,REIMB,SIR,Maintenance,Managers/Supervisors,1.00
4,row-qfu8~pipn-63fh,rv-r95q~v5cu.pyy5,2026-09-01 18:37:12.606000+00:00,2026-09-01 18:37:12.606000+00:00,2026,2026-07-01T00:00:00.000,Actual,2026,NREIMB,SIR,Maintenance,Managers/Supervisors,31.00
5,row-j7mc_8855~q9ny,rv-ca9a_4xg3-kfdm,2026-09-01 18:37:12.606000+00:00,2026-09-01 18:37:12.606000+00:00,2026,2026-07-01T00:00:00.000,Actual,2026,REIMB,MNR,Administration,Managers/Supervisors,11.16
6,row-a66f_chud~i7za,rv-iqhx-er8e.z8a9,2026-09-01 18:37:12.606000+00:00,2026-09-01 18:37:12.606000+00:00,2026,2026-07-01T00:00:00.000,Actual,2026,REIMB,MTABC,Public Safety,Managers/Supervisors,0.00
7,row-6e5p-begb~di7r,rv-ywch-6xj3.7gkb,2026-09-01 18:37:12.606000+00:00,2026-09-01 18:37:12.606000+00:00,2026,2026-07-01T00:00:00.000,Actual,2026,REIMB,NYCT,Administration,Operational Hourlies,0.00
8,row-af8i_q744_ga29,rv-b6d5~ssyv-7mgs,2026-09-01 18:37:12.606000+00:00,2026-09-01 18:37:12.606000+00:00,2026,2026-07-01T00:00:00.000,Actual,2026,NREIMB,NYCT,Engineering,Managers/Supervisors,2.28
9,row-drku~kgyg_t7w8,rv-erni-pme4.qw77,2026-09-01 18:37:12.606000+00:00,2026-09-01 18:37:12.606000+00:00,2026,2026-07-01T00:00:00.000,Actual,2026,REIMB,MTABC,Public Safety,Operational Hourlies,0.00
10,row-kczf.yunf-88d3,rv-mwmd~9ztn.ewr3,2026-09-01 18:37:12.606000+00:00,2026-09-01 18:37:12.606000+00:00,2026,2026-07-01T00:00:00.000,Actual,2026,NREIMB,LIRR,Engineering,Managers/Supervisors,20.30

**json_data2 represents the following:**

dataset containing information about the number of subway trains delayed per day type (Weekdays and weekends) in a month, broken down into specific delay categories.

**Columns**

**1.   :id**

      *  lists the unique name associated with the row so systems can find, update, or delete that exact record should it be required for JSON.
**2.   :version**

      *   lists how the row is tracked for changes in content ensuring the JSON code knows how to process older or newer formats safely

**3.   :created_at**

       *   lists the timestamp of when the data was first added for JSON
**4.   :updated_at**

       *   lists the timestamp of when the data was updated for JSON
**5.   fiscal_year**

       *   lists the fiscal year of the data
**6.   month**

       *   lists the month of the data, rounded up to the first day of the month. EX: 2023-01-01
**7.   division**

       *   lists whether if the data is from the A division (numbered subway lines and S 42nd) and B division (lettered subway lines)

**8.   line**

       *   lists the subway line (1, 2, 3, 4, 5, 6, 7, A, C, E, B, D, F, M, G, JZ, L, N, Q, R, S 42nd, S Rock, S Fkln).
**9.   day_type**

       *   lists weekdays as 1 and weekends as 2

**10.   		reporting_category**

       *   lists the six categories that delays are reported under are Crew Availability, External Factors, Infrastructure & Equipment, Operating Conditions, Planned ROW Work, and Police & Medical.

**11.  		delays**

       *   lists The number of train delays per reporting category, line, and month.


**What does the code do?**

first, variable df8 is initialized and is assigned to the pd module using dot notation to call the read_excel function passing json_data2 as an argument.

we need this line of code so that pandas can read our dataset which in this case is a JSON file

second, we call our assigned variable and use dot notation again to call the head function with an argument of 11

NOTE: Python uses zero indexing, meaning anything like lists/arrays start at 0.
NOTE: you do not need to import JSON, just use pandas's read_json function

In [12]:
df8 = pd.read_json(json_data2)
df8.head(11)

,:id,:version,:created_at,:updated_at,month,division,line,day_type,reporting_category,delays
0,row-qzkn_x4hv-hwpy,rv-c25r_djw8_c2vr,2026-08-28 15:35:35.343000+00:00,2026-08-28 15:35:35.343000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,1,Crew Availability,17
1,row-dgct.w4ii.8nhg,rv-uj7f_wgm9-nc5k,2026-08-28 15:35:35.343000+00:00,2026-08-28 15:35:35.343000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,1,Infrastructure & Equipment,400
2,row-stwi.i5gt-inku,rv-he4w-3x9t.cc8t,2026-08-28 15:35:35.343000+00:00,2026-08-28 15:35:35.343000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,1,Operating Conditions,332
3,row-grq7.n3nu.5hst,rv-4w5w~9x4v.igwq,2026-08-28 15:35:35.343000+00:00,2026-08-28 15:35:35.343000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,1,External Factors,314
4,row-f82e-9dry_z4mc,rv-8phe-8vkz.nsn4,2026-08-28 15:35:35.343000+00:00,2026-08-28 15:35:35.343000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,1,Police & Medical,345
5,row-d2x5.wywm-4yzj,rv-dtx6_zub3-dgfp,2026-08-28 15:35:35.343000+00:00,2026-08-28 15:35:35.343000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,1,Planned ROW Work,111
6,row-gipb-ky6e_qzmd,rv-g5y4.n2d8-54bs,2026-08-28 15:35:35.343000+00:00,2026-08-28 15:35:35.343000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,2,Crew Availability,10
7,row-urwu-r2uc-8x73,rv-gyqh_7rz5_j2xm,2026-08-28 15:35:35.343000+00:00,2026-08-28 15:35:35.343000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,2,Planned ROW Work,18
8,row-ws2b_r356~inja,rv-5ie5_kae7-z7j3,2026-08-28 15:35:35.343000+00:00,2026-08-28 15:35:35.343000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,2,Police & Medical,42
9,row-vpw2~4h36_ecqy,rv-r6a7_f9jz.zy2r,2026-08-28 15:35:35.343000+00:00,2026-08-28 15:35:35.343000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,2,Infrastructure & Equipment,78
10,row-cc4r~qt2f_nd9s,rv-e8sw~xbap-g2xr,2026-08-28 15:35:35.343000+00:00,2026-08-28 15:35:35.343000+00:00,2020-01-01T00:00:00.000,A DIVISION,1,2,Operating Conditions,36

**json_data3 represents the following:**


dataset containing information about the number of subway trains delayed per day type (Weekdays and weekends) in a month, broken down into specific delay categories.

**Columns**

**1.   :id**

      *  lists the unique name associated with the row so systems can find, update, or delete that exact record should it be required for JSON.
**2.   :version**

      *   lists how the row is tracked for changes in content ensuring the JSON code knows how to process older or newer formats safely

**3.   :created_at**

       *   lists the timestamp of when the data was first added for JSON
**4.   :updated_at**

       *   lists the timestamp of when the data was updated for JSON
**5.   county**

       *   lists the county in which the licensed entity is physically located
**6.   license_number**

       *   lists the licensed entity’s license number for this location
**7.  	operation_type**

       *   lists the type of operation the licensed entity conducts

**8.   	estab_type**

       *   lists the establishment type for the licensed entity at this location; see document in ‘About’ section, or go to https://data.ny.gov/api/views/9a8c-vfzj/files/UBDP3oW2f-K767I4f51EJaIUO8eNGPrAQQj8tSvBhbo?download=true&filename=NYSDAM_RetailFoodStoresEstablishmentTypeCodes.pdf.
**9.   	entity_name**

       *   lists the name of the licensed entity

**10.   			dba_name**

       *   lists the “Doing business as” (DBA) name for the licensed entity

**11.  			street_number**

       *   lists the street number for the physical address of the licensed entity; will be blank if no data is recorded
**12.  			street_name**

       *   lists the street name for the physical location of the licensed entity; the first address line recorded.
**13.  				city**

       *   lists the name of the city in which the licensed entity is physically located.
**14.  				state**

       *   lists the two character state code for the physical location of the licensed entity.
**15.  				zip_code**

       *   lists the United States Postal Service (USPS) ZIP code for the physical location of the licensed entity.
**16.  				georeference**

       *   lists the Open Data platform-generated geocoding information from supplied address components. Point-type location is the centroid of the address components provided and does not reflect a specific address if the street address component is not provided. Point-type location is supplied in "POINT ( )" format.
**17.  					:@computed_region_yamh_8v7k**

       *   lists the internal metadata column used by the Socrata open data platform. It automatically maps geographical coordinates to a specific administrative region.
**18.  					square_footage**

       *   lists the square footage of the entire physical location of the licensed entity
**19.  					address_line_2**

       *   lists the second address line recorded for the physical location of the licensed entity; blank if no data is recorded
**20.  					address_line_3**

       *   lists the third address line recorded for the physical location of the licensed entity; blank if no data is recorded.

**What does the code do?**

first, variable df9 is initialized and is assigned to the pd module using dot notation to call the read_excel function passing json_data3 as an argument.

we need this line of code so that pandas can read our dataset which in this case is a JSON file

second, we call our assigned variable and use dot notation again to call the head function with an argument of 11

NOTE: Python uses zero indexing, meaning anything like lists/arrays start at 0.
NOTE: you do not need to import JSON, just use pandas's read_json function

In [13]:
df9 = pd.read_json(json_data3)
df9.head(11)

,:id,:version,:created_at,:updated_at,county,license_number,operation_type,estab_type,entity_name,dba_name,street_number,street_name,city,state,zip_code,georeference,:@computed_region_yamh_8v7k,square_footage,address_line_2,address_line_3
0,row-hjvm.fhhu.pqkk,rv-35uf_acrr.q8vt,2025-09-30 15:15:12.620000+00:00,2025-09-30 15:15:40.967000+00:00,RICHMOND,768379,Store,A,CRATE & GO INC,CRATE & GO,520,FOREST AVE,STATEN ISLAND,NY,10310,"{'type': 'Point', 'coordinates': [-74.10763, 4...",585.0,NaN,NaN,NaN
1,row-3hms_w5tj_x4g2,rv-fk9w-n6hz_ewnb,2025-09-30 15:15:12.620000+00:00,2025-09-30 15:15:40.967000+00:00,BRONX,768373,Store,A,2490 GROCERY HOUSEWARE CORP,2490 GROCERY HOUSEWARE,2490,WILLIAMSBRIDGE RD,BRONX,NY,10469,"{'type': 'Point', 'coordinates': [-73.85786, 4...",307.0,NaN,NaN,NaN
2,row-rg97.byfs.9cz4,rv-4de3_ridp.2hii,2025-09-30 15:15:12.620000+00:00,2025-09-30 15:15:40.967000+00:00,QUEENS,768372,Store,A,AJ&E 99UP SUPERMARKET INC,AJ&E 99UP SUPERMARKET,47-06,BELL BLVD,BAYSIDE,NY,11361,"{'type': 'Point', 'coordinates': [-73.7676, 40...",196.0,NaN,NaN,NaN
3,row-i6ze.yet4_imqt,rv-96hp.idep~ww6f,2025-09-30 15:15:12.620000+00:00,2025-09-30 15:15:40.967000+00:00,SUFFOLK,768319,Store,A,HAPPY AFRICAN MARKET LLC,HAPPY AFRICAN MARKET,16,LOWELL AVENUE,ISLIP TERRACE,NY,11752,"{'type': 'Point', 'coordinates': [-73.17418, 4...",1019.0,NaN,NaN,NaN
4,row-9n3v_98xq_q7jw,rv-tyda_iq4v.pjwf,2025-09-30 15:15:12.620000+00:00,2025-09-30 15:15:40.967000+00:00,ALBANY,768238,Store,A,TRADER JOES EAST INC,TRADER JOES #579,388,FEURA BUSH RD SUITE 200,GLENMONT,NY,12077,"{'type': 'Point', 'coordinates': [-73.79517, 4...",837.0,NaN,NaN,NaN
5,row-ggq5~tdiw_g8x9,rv-yaxn-cgc7.s7gy,2025-09-30 15:15:12.620000+00:00,2025-09-30 15:15:40.967000+00:00,OSWEGO,768208,Store,AC,FRUIT VALLEY ORCHARD AND FARM LLC,FRUIT VALLEY ORCHARD,507,BUNKER HILL,OSWEGO,NY,13126,"{'type': 'Point', 'coordinates': [-76.55412, 4...",239.0,500.0,NaN,NaN
6,row-r9mt.f7eh_u5w9,rv-69b7~gczz_7vrg,2025-09-30 15:15:12.620000+00:00,2025-09-30 15:15:40.967000+00:00,ERIE,768204,Store,A,BURLEY BROTHERS COUNTRY BUTCHERY LLC,BURLEY BROTHERS COUNTRY BUTCHERY,3218,TRANSIT ROAD####,BUFFALO,NY,14224,"{'type': 'Point', 'coordinates': [-78.69695, 4...",276.0,NaN,NaN,NaN
7,row-9ecy_acnt.xzqa,rv-59bc~3mmz~6zex,2025-09-30 15:15:12.620000+00:00,2025-09-30 15:15:40.967000+00:00,ONONDAGA,768184,Store,AC,ON THE WAY 2 INC,ON THE WAY 2,711,S MAIN ST ####,SYRACUSE,NY,13212,"{'type': 'Point', 'coordinates': [-76.14117, 4...",703.0,NaN,NaN,NaN
8,row-ua5f-uv23.x8fa,rv-yu4t_82hi-fq4y,2025-09-30 15:15:12.620000+00:00,2025-09-30 15:15:40.967000+00:00,RICHMOND,768136,Store,A,TRADER JOES EAST INC,TRADER JOES #580,6400,AMBOY RD,STATEN ISLAND,NY,10309,"{'type': 'Point', 'coordinates': [-74.21555, 4...",585.0,NaN,NaN,NaN
9,row-hspg~rjgv.v7w3,rv-5t47.ydiz~afht,2025-09-30 15:15:12.620000+00:00,2025-09-30 15:15:40.967000+00:00,WESTCHESTER,768123,Store,A,SIAR USA LLC,ALBANIAN CONVENIENCE 10/1/2025,4,TUCKAHOE RD ##,YONKERS,NY,10710,"{'type': 'Point', 'coordinates': [-73.87069, 4...",948.0,NaN,NaN,NaN
10,row-fmg8_zj2c~rsfa,rv-p6e7_86pn_2adg,2025-09-30 15:15:12.620000+00:00,2025-09-30 15:15:40.967000+00:00,RICHMOND,768120,Store,AC,NEIGHBORHOOD CHANGE YOUTH ORG INC,MOTHERR NATURE'S GARDEN,372,BROADWAY,STATEN ISLAND,NY,10310,"{'type': 'Point', 'coordinates': [-74.11671, 4...",585.0,600.0,NaN,NaN